server:
  port: 8090
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data_test?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379
    password: foobared
    database: 1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

department:
  name: 网络安全基地
  fabric-id: Department1

fabric:
  mspId: Org1MSP
  certificatePath: D:/Desktop/lts/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem
  privateKeyPath: D:/Desktop/lts/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk
  tlsCertPath: D:/Desktop/lts/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
  channel: mychannel
  contract: DataAsset
  ip: 192.168.56.128:7051
  name: peer0.org1.example.com

ipfs:
  ip: 222.20.126.154
  port: 5000

feignUrl: 127.0.0.1:8082

